// ── User / Auth ──

export interface User {
  id: string;
  email: string;
  displayName: string | null;
  avatarUrl: string | null;
  timezone: string;
  language: string;
  theme: "dark" | "light";
  onboardingStep: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Session {
  id: string;
  userId: string;
  refreshToken: string;
  expiresAt: string;
  createdAt: string;
}

// ── AI / Chat ──

export interface Conversation {
  id: string;
  userId: string;
  channel: "web" | "whatsapp" | "api";
  title: string | null;
  createdAt: string;
  updatedAt: string;
  messages?: Message[];
}

export interface Message {
  id: string;
  conversationId: string;
  role: "user" | "assistant" | "system" | "tool";
  content: string;
  toolCalls?: ToolCall[];
  toolResults?: ToolResult[];
  referencedMemoryNodes: string[];
  tokensUsed?: number;
  modelUsed?: string;
  latencyMs?: number;
  createdAt: string;
}

export interface ToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

export interface ToolResult {
  toolCallId: string;
  output: unknown;
}

export interface StreamingMessage {
  id: string;
  role: "assistant";
  content: string;
  memoryLinks?: MemoryLink[];
  isComplete: boolean;
}

// ── Second Brain / Memory ──

export interface MemoryNode {
  id: string;
  userId: string;
  type: "fact" | "preference" | "pattern" | "relation" | "daily_note" | "agent_output";
  title: string;
  content: string;
  layers?: ProgressiveSummarizationLayers;
  tags: string[];
  links?: MemoryLink[];
  metadata: MemoryMetadata;
  reviewInterval: number;
  nextReviewAt?: string;
  lastReviewedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProgressiveSummarizationLayers {
  l1Summary: string;
  l2Highlights?: string[];
  l3Full?: string;
  l4Compressed?: string;
}

export interface MemoryMetadata {
  confidence: number;
  accessCount: number;
  source: "explicit" | "inferred" | "learned";
  reviewStatus: "current" | "due" | "overdue" | "archived";
}

export interface MemoryLink {
  id: string;
  sourceId: string;
  targetId: string;
  linkType: LinkType;
  label: string | null;
  context: string | null;
  strength: number;
  confidence: number;
  isAutoGenerated: boolean;
  createdAt: string;
}

export type LinkType =
  | "related_to"
  | "categorized_as"
  | "causes"
  | "contradicts"
  | "mentioned_in"
  | "supports"
  | "follows_from"
  | "user_defined";

export interface DailyNote {
  id: string;
  userId: string;
  noteDate: string;
  highlights: string[];
  decisions: DailyNoteDecision[];
  connectionsMade: DailyNoteConnection[];
  metrics: DailyNoteMetrics;
  aiReflection: string | null;
  isFinalized: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface DailyNoteDecision {
  description: string;
  relatedNodeId?: string;
  approved: boolean;
}

export interface DailyNoteConnection {
  fromNode: string;
  toNode: string;
  linkType: LinkType;
}

export interface DailyNoteMetrics {
  emailsProcessed: number;
  tasksCompleted: number;
  agentRuns: number;
  newMemories: number;
  newLinks: number;
}

// ── Agents ──

export interface Agent {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  definition: AgentDefinition;
  version: number;
  status: "draft" | "active" | "paused" | "archived";
  isPublished: boolean;
  totalRuns: number;
  successRate: number;
  createdAt: string;
  updatedAt: string;
}

export interface AgentDefinition {
  triggers: AgentTrigger[];
  blocks: AgentBlock[];
  edges: AgentEdge[];
}

export interface AgentTrigger {
  type: "schedule" | "webhook" | "event";
  config: Record<string, unknown>;
}

export interface AgentBlock {
  id: string;
  type: "trigger" | "ai" | "action" | "logic" | "connector";
  subtype: string;
  config: Record<string, unknown>;
  position: { x: number; y: number };
}

export interface AgentEdge {
  id: string;
  source: string;
  target: string;
  label?: string;
}

export interface AgentRun {
  id: string;
  agentId: string;
  userId: string;
  triggerType: "manual" | "schedule" | "webhook" | "event";
  status: "running" | "completed" | "failed" | "cancelled";
  inputData: unknown;
  outputData: unknown;
  errorMessage: string | null;
  steps: unknown[];
  memoryNodesCreated: number;
  memoryLinksCreated: number;
  startedAt: string;
  completedAt: string | null;
  durationMs: number | null;
  costCents: number;
}

// ── Integrations ──

export interface Integration {
  id: string;
  userId: string;
  connectorType: string;
  displayName: string;
  status: "active" | "error" | "disconnected";
  scopes: string[];
  lastSyncAt: string | null;
  createdAt: string;
}

export interface Connector {
  id: string;
  key: string;
  name: string;
  description: string | null;
  iconUrl: string | null;
  authType: "oauth2" | "apikey" | "basic";
  isBuiltin: boolean;
}

// ── Marketplace ──

export interface MarketplaceListing {
  id: string;
  agentId: string;
  userId: string;
  title: string;
  description: string | null;
  priceCents: number;
  category: string;
  tags: string[];
  ratingAvg: number;
  ratingCount: number;
  installCount: number;
  status: "draft" | "published" | "unpublished";
  createdAt: string;
}

export interface MarketplaceReview {
  id: string;
  listingId: string;
  userId: string;
  rating: number;
  review: string | null;
  createdAt: string;
}

// ── Teams ──

export interface Team {
  id: string;
  name: string;
  ownerId: string;
  createdAt: string;
}

export interface TeamMember {
  id: string;
  teamId: string;
  userId: string;
  role: "owner" | "admin" | "member" | "viewer";
  createdAt: string;
}

// ── Billing ──

export interface Plan {
  id: string;
  name: "free" | "pro" | "business";
  priceMonthlyCents: number;
  maxAgents: number | null;
  maxIntegrations: number | null;
  maxTeamMembers: number | null;
  maxMemoryNodes: number | null;
  features: Record<string, unknown>;
}

export interface Subscription {
  id: string;
  userId: string;
  planId: string;
  status: "active" | "past_due" | "cancelled";
  currentPeriodStart: string;
  currentPeriodEnd: string;
  createdAt: string;
}

// ── Notifications ──

export interface Notification {
  id: string;
  userId: string;
  type: string;
  title: string;
  body: string | null;
  data: unknown;
  relatedMemoryNode: string | null;
  isRead: boolean;
  channel: "in_app" | "whatsapp" | "email";
  createdAt: string;
}

// ── WebSocket ──

export type WSEventType =
  | "agent.running"
  | "agent.completed"
  | "agent.error"
  | "agent.step"
  | "ai.message_chunk"
  | "ai.morning_briefing"
  | "notification"
  | "integration.status"
  | "brain.node_created"
  | "brain.node_updated"
  | "brain.link_created"
  | "brain.review_due"
  | "brain.daily_note_ready";

export interface WSEvent {
  type: WSEventType;
  data: unknown;
  timestamp: string;
}

// ── UI ──

export type Theme = "dark" | "light";

export type ToastType = "success" | "error" | "warning" | "info";

export interface Toast {
  id: string;
  type: ToastType;
  title: string;
  message?: string;
  duration?: number;
}
