"use client";

import { create } from "zustand";
import { api } from "@/lib/api";
import type { MemoryNode, MemoryLink, DailyNote } from "@/types";

// ─── Types ──────────────────────────────────────────────────────────────────────

interface GraphNode {
  id: string;
  title: string;
  type: string;
  tags: string[];
  linksCount: number;
  isOrphan: boolean;
  paraCategory?: string;
  createdAt: string;
  summary?: string;
}

interface GraphEdge {
  id: string;
  source: string;
  target: string;
  linkType: string;
  label?: string;
  strength: number;
  confidence: number;
  isAutoGenerated: boolean;
}

interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
  metadata?: {
    totalNodes: number;
    totalEdges: number;
    orphanCount: number;
  };
}

interface FilterState {
  tags: string[];
  types: string[];
  searchQuery: string;
  dateRange: [string, string] | null;
}

interface ViewportState {
  zoom: number;
  centerX: number;
  centerY: number;
}

interface BrainStats {
  totalNodes: number;
  totalLinks: number;
  orphanCount: number;
  graphDensity: number;
  weeklyGrowth: {
    newNodes: number;
    newLinks: number;
    reviewsCompleted: number;
  };
  tags: { tag: string; count: number }[];
  typeDistribution: Record<string, number>;
  healthScore: number;
}

interface ReviewItem {
  id: string;
  title: string;
  content: string;
  layers: Record<string, unknown>;
  tags: string[];
  type: string;
  reviewInterval: number;
  nextReviewAt: string | null;
  lastReviewedAt: string | null;
  daysSinceReview: number | null;
  recentReviews: {
    rating: string;
    intervalBefore: number;
    intervalAfter: number;
    createdAt: string;
  }[];
  linksCount: number;
}

interface BrainState {
  // Graph data
  graphData: GraphData | null;
  localGraphData: GraphData | null;
  isLoadingGraph: boolean;
  isLoadingLocalGraph: boolean;

  // Selected node
  selectedNodeId: string | null;
  selectedNodeDetail: MemoryNode | null;
  isLoadingNodeDetail: boolean;

  // Filters
  filters: FilterState;

  // Viewport
  viewport: ViewportState;

  // Stats
  stats: BrainStats | null;
  isLoadingStats: boolean;

  // Review queue
  reviewQueue: ReviewItem[];
  isLoadingReviewQueue: boolean;

  // Daily notes
  dailyNote: DailyNote | null;
  dailyNoteHistory: DailyNote[];
  isLoadingDailyNote: boolean;

  // Search results
  searchResults: MemoryNode[];
  isSearching: boolean;

  // ── Actions ──
  loadGraph: () => Promise<void>;
  loadLocalGraph: (nodeId: string, depth?: number) => Promise<void>;
  selectNode: (nodeId: string | null) => void;
  loadNodeDetail: (nodeId: string) => Promise<void>;
  createLink: (sourceId: string, targetId: string, linkType?: string) => Promise<MemoryLink | null>;
  removeLink: (linkId: string) => Promise<void>;
  setFilter: (filters: Partial<FilterState>) => void;
  setViewport: (viewport: Partial<ViewportState>) => void;
  searchNodes: (query: string, tags?: string[], types?: string[]) => Promise<void>;
  loadStats: () => Promise<void>;
  loadReviewQueue: () => Promise<void>;
  loadDailyNote: () => Promise<void>;
  loadDailyNoteHistory: (days?: number) => Promise<void>;
  createNode: (data: Partial<MemoryNode>) => Promise<MemoryNode | null>;
  deleteNode: (nodeId: string) => Promise<void>;
}

// ─── Store ───────────────────────────────────────────────────────────────────────

const initialFilters: FilterState = {
  tags: [],
  types: [],
  searchQuery: "",
  dateRange: null,
};

const initialViewport: ViewportState = {
  zoom: 1,
  centerX: 0,
  centerY: 0,
};

export const useBrainStore = create<BrainState>((set, get) => ({
  // ── State ──
  graphData: null,
  localGraphData: null,
  isLoadingGraph: false,
  isLoadingLocalGraph: false,
  selectedNodeId: null,
  selectedNodeDetail: null,
  isLoadingNodeDetail: false,
  filters: { ...initialFilters },
  viewport: { ...initialViewport },
  stats: null,
  isLoadingStats: false,
  reviewQueue: [],
  isLoadingReviewQueue: false,
  dailyNote: null,
  dailyNoteHistory: [],
  isLoadingDailyNote: false,
  searchResults: [],
  isSearching: false,

  // ── Actions ──

  loadGraph: async () => {
    set({ isLoadingGraph: true });
    try {
      const response = await api.get<GraphData>("/api/v1/brain/graph");
      set({ graphData: response, isLoadingGraph: false });
    } catch (err) {
      console.error("Failed to load graph:", err);
      set({ isLoadingGraph: false });
    }
  },

  loadLocalGraph: async (nodeId, depth = 2) => {
    set({ isLoadingLocalGraph: true });
    try {
      const response = await api.get<GraphData>(
        `/api/v1/brain/graph/local/${nodeId}`,
        { params: { depth } },
      );
      set({ localGraphData: response, isLoadingLocalGraph: false });
    } catch (err) {
      console.error("Failed to load local graph:", err);
      set({ isLoadingLocalGraph: false });
    }
  },

  selectNode: (nodeId) => {
    set({ selectedNodeId: nodeId });
    if (nodeId) {
      get().loadNodeDetail(nodeId);
    } else {
      set({ selectedNodeDetail: null });
    }
  },

  loadNodeDetail: async (nodeId) => {
    set({ isLoadingNodeDetail: true });
    try {
      const response = await api.get<{ node: MemoryNode }>(
        `/api/v1/brain/nodes/${nodeId}`,
      );
      set({ selectedNodeDetail: response.node, isLoadingNodeDetail: false });
    } catch (err) {
      console.error("Failed to load node detail:", err);
      set({ isLoadingNodeDetail: false });
    }
  },

  createLink: async (sourceId, targetId, linkType = "related_to") => {
    try {
      const response = await api.post<{ link: MemoryLink }>(
        "/api/v1/brain/links",
        {
          source_id: sourceId,
          target_id: targetId,
          link_type: linkType,
        },
      );
      // Refresh graph data
      get().loadGraph();
      return response.link;
    } catch (err) {
      console.error("Failed to create link:", err);
      return null;
    }
  },

  removeLink: async (linkId) => {
    try {
      await api.delete(`/api/v1/brain/links/${linkId}`);
      get().loadGraph();
    } catch (err) {
      console.error("Failed to remove link:", err);
    }
  },

  setFilter: (filters) => {
    set((state) => ({
      filters: { ...state.filters, ...filters },
    }));
  },

  setViewport: (viewport) => {
    set((state) => ({
      viewport: { ...state.viewport, ...viewport },
    }));
  },

  searchNodes: async (query, tags, types) => {
    set({ isSearching: true });
    try {
      const response = await api.post<{ nodes: MemoryNode[]; total: number }>(
        "/api/v1/brain/graph/search",
        { query, tags, types, limit: 50 },
      );
      set({ searchResults: response.nodes, isSearching: false });
    } catch (err) {
      console.error("Search failed:", err);
      set({ isSearching: false });
    }
  },

  loadStats: async () => {
    set({ isLoadingStats: true });
    try {
      const response = await api.get<{ stats: BrainStats }>(
        "/api/v1/brain/stats",
      );
      set({ stats: response.stats, isLoadingStats: false });
    } catch (err) {
      console.error("Failed to load stats:", err);
      set({ isLoadingStats: false });
    }
  },

  loadReviewQueue: async () => {
    set({ isLoadingReviewQueue: true });
    try {
      const response = await api.get<{ queue: ReviewItem[] }>(
        "/api/v1/brain/review",
        { params: { limit: 20 } },
      );
      set({ reviewQueue: response.queue, isLoadingReviewQueue: false });
    } catch (err) {
      console.error("Failed to load review queue:", err);
      set({ isLoadingReviewQueue: false });
    }
  },

  loadDailyNote: async () => {
    set({ isLoadingDailyNote: true });
    try {
      const response = await api.get<{ note: DailyNote }>(
        "/api/v1/brain/daily",
      );
      set({ dailyNote: response.note, isLoadingDailyNote: false });
    } catch (err) {
      console.error("Failed to load daily note:", err);
      set({ isLoadingDailyNote: false });
    }
  },

  loadDailyNoteHistory: async (days = 30) => {
    try {
      const response = await api.get<DailyNote[]>(
        `/api/v1/brain/daily/history`,
        { params: { days } },
      );
      set({ dailyNoteHistory: response });
    } catch (err) {
      console.error("Failed to load daily note history:", err);
    }
  },

  createNode: async (data) => {
    try {
      const response = await api.post<{ node: MemoryNode }>(
        "/api/v1/brain/nodes",
        data,
      );
      get().loadStats();
      return response.node;
    } catch (err) {
      console.error("Failed to create node:", err);
      return null;
    }
  },

  deleteNode: async (nodeId) => {
    try {
      await api.delete(`/api/v1/brain/nodes/${nodeId}`);
      get().loadStats();
      get().loadGraph();
      set({ selectedNodeId: null, selectedNodeDetail: null });
    } catch (err) {
      console.error("Failed to delete node:", err);
    }
  },
}));
